"""

Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"""
numbers = [0, 1]
answer = []
while numbers[len(numbers)-1] + numbers[len(numbers)-2] < 4000001:
	numbers.append(numbers[len(numbers)-1] + numbers[len(numbers)-2])
answer = [i for i in numbers if i%2 == 0]

print sum(answer)